"""A desktop front end for the abCA command line.

DESIGN RULE: THE GUI IS DERIVED FROM THE CLI, NEVER COPIED FROM IT
==================================================================
Every form in this window is generated by walking the Typer/Click command tree
at start-up (:mod:`abca.gui.surface`). There is no hand-written list of options
anywhere in this package. That is not laziness -- it is the only way the promise
"the GUI does everything the CLI does" can be kept and TESTED: a test walks the
same tree and asserts every command and every parameter has a form control.
Add an option to the CLI and it appears here without anyone remembering to.

The GUI also never re-implements a command. It builds the exact argv the user
would have typed (:mod:`abca.gui.argv`), shows it, and runs the real CLI as a
subprocess (:mod:`abca.gui.runner`). Two consequences matter:

* **Nothing the GUI does is unreproducible from a terminal.** The "command"
  box is copy-paste-able, and a run started from the window writes the same
  ledger record, with the same hashes, as the same command typed by hand.
* **The GUI cannot corrupt the analysis.** A crash in the window is a crash in
  a different process from the one holding the run ledger.

Standard library only (``tkinter``), for the same reason the CLI has three
dependencies: every package added is a package the reproducibility story has to
account for.
"""

from abca.gui.surface import CommandSpec, ParamSpec, describe_cli

__all__ = ["CommandSpec", "ParamSpec", "describe_cli"]
